server:
    port:  8300


spring:
    application:
        name: conver-server
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?setUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: 123456


mybatis:
  type-aliases-package: com.conver.server.entity
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    cache-enabled: true
    # 下划线转驼峰
    map-underscore-to-camel-case: true

