server:
    port:  8300

spring:
    application:
        name: conver-server
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver: com.mysql.jdbc.Driver
        username: dev
        password: dev
        url: jdbc:mysql://172.17.33.223:3306/test1?useSSL=false&tinyInt1isBit=false
       # url: jdbc:mysql://localhost:3306/test?setUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
       # username: root
       # password: 123456




